### The iris data set 

In [3]:
import numpy as np  
import pandas as pd  
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

iris = load_iris()
df=pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['target']=iris.target
df['species']=df['target'].apply(lambda x: iris.target_names[x])
df.head(25)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 5.1               3.5                1.4               0.2   
1                 4.9               3.0                1.4               0.2   
2                 4.7               3.2                1.3               0.2   
3                 4.6               3.1                1.5               0.2   
4                 5.0               3.6                1.4               0.2   
5                 5.4               3.9                1.7               0.4   
6                 4.6               3.4                1.4               0.3   
7                 5.0               3.4                1.5               0.2   
8                 4.4               2.9                1.4               0.2   
9                 4.9               3.1                1.5               0.1   
10                5.4               3.7                1.5               0.2   
11                4.8               3.4                1.6               0.2   
12                4.8               3.0                1.4               0.1   
13                4.3               3.0                1.1               0.1   
14                5.8               4.0                1.2               0.2   
15                5.7               4.4                1.5               0.4   
16                5.4               3.9                1.3               0.4   
17                5.1               3.5                1.4               0.3   
18                5.7               3.8                1.7               0.3   
19                5.1               3.8                1.5               0.3   
20                5.4               3.4                1.7               0.2   
21                5.1               3.7                1.5               0.4   
22                4.6               3.6                1.0               0.2   
23                5.1               3.3                1.7               0.5   
24                4.8               3.4                1.9               0.2   

    target species  
0        0  setosa  
1        0  setosa  
2        0  setosa  
3        0  setosa  
4        0  setosa  
5        0  setosa  
6        0  setosa  
7        0  setosa  
8        0  setosa  
9        0  setosa  
10       0  setosa  
11       0  setosa  
12       0  setosa  
13       0  setosa  
14       0  setosa  
15       0  setosa  
16       0  setosa  
17       0  setosa  
18       0  setosa  
19       0  setosa  
20       0  setosa  
21       0  setosa  
22       0  setosa  
23       0  setosa  
24       0  setosa

### Confustion Matrix

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score 

#select features and targets 
x=df.drop(['target','species'], axis=1)
y=df['species']

# Split the data into train and test
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

#initialize the scalar 
scalar= StandardScaler() 

#Fit and transform the training data
x_train_scaled = scalar.fit_transform(x_train)

print(f'Scaled X_Train: {x_train_scaled}')

#initialize the logistic Regression Model 
log_reg = LogisticRegression() 

#Fit the model
log_reg.fit(x_train_scaled, y_train)    

#Predict on the test data
y_pred=log_reg.predict(x_train_scaled)

print(y_pred, y_test)


Scaled X_Train: [[-1.47393679  1.20365799 -1.56253475 -1.31260282]
 [-0.13307079  2.99237573 -1.27600637 -1.04563275]
 [ 1.08589829  0.08570939  0.38585821  0.28921757]
 [-1.23014297  0.75647855 -1.2187007  -1.31260282]
 [-1.7177306   0.30929911 -1.39061772 -1.31260282]
 [ 0.59831066 -1.25582892  0.72969227  0.95664273]
 [ 0.72020757  0.30929911  0.44316389  0.4227026 ]
 [-0.74255534  0.98006827 -1.27600637 -1.31260282]
 [-0.98634915  1.20365799 -1.33331205 -1.31260282]
 [-0.74255534  2.32160658 -1.27600637 -1.44608785]
 [-0.01117388 -0.80864948  0.78699794  0.95664273]
 [ 0.23261993  0.75647855  0.44316389  0.55618763]
 [ 1.08589829  0.08570939  0.55777524  0.4227026 ]
 [-0.49876152  1.87442714 -1.39061772 -1.04563275]
 [-0.49876152  1.4272477  -1.27600637 -1.31260282]
 [-0.37686461 -1.47941864 -0.01528151 -0.24472256]
 [ 0.59831066 -0.58505976  0.78699794  0.4227026 ]
 [ 0.72020757  0.08570939  1.01622064  0.8231577 ]
 [ 0.96400139 -0.13788033  0.38585821  0.28921757]
 [ 1.69538284  

In [7]:
confusion_matrix = confusion_matrix(y_test, y_pred)
print(f'Confusion Matrix: {confusion_matrix}')

#classification Report 
classification_report = classification_report(y_test, y_pred)

ValueError: Found input variables with inconsistent numbers of samples: [30, 120]